<style>
	.form-select{
		min-width: 100%;
	}
</style>
<div class="apd-pengelasan">
	<!-- SARUNG TANGAN CAT-->
	<div class="card-body mt-3 shadow rounded">
		<h4>Sarung Tangan Pengecatan</h4>
		<div class="row">
			<div class="col-md-6">
				<div class="form-group">

					<!--Ada/Tidak -->
					<div class="row mt-2">
						<div class="col-sm-4">
							<label>Ada/Tidak</label>
						</div>
						<div class="col-sm-8">
							<select class="form-select form-select-lg" aria-label="cat-ada-tidak">
							  <option value="">Ada</option>
							  <option value="">Tidak</option>
							</select>		 
				   		</div>
					</div>
				</div>
    		</div>

    		<!--KONDISI -->
    		<div class="col-md-6">
				<div class="form-group">
					<div class="row mt-2">
						<div class="col-sm-4">
							<label>Kondisi</label>
						</div>
						<div class="col-sm-8">
							<select class="form-select form-select-lg" aria-label="kondisi">
							  <option value="">Layak</option>
							  <option value="">Tidak Layak</option>
							</select>		 
					   	</div>
					</div>
				</div>
    		</div>
		</div>
	</div>

	<!-- MASKER RESPIRATOR -->
	<div class="card-body mt-3 shadow rounded">
		<h4>Masker Respirator</h4>
		<div class="row">
			<div class="col-md-6">
				<div class="form-group">
				<!--Ada/Tidak -->
					<div class="row mt-2">
						<div class="col-sm-4">
							<label>Ada/Tidak</label>
						</div>
						<div class="col-sm-8">
							<select class="form-select form-select-lg" aria-label="respirator-ada-tidak">
							  <option value="">Ada</option>
							  <option value="">Tidak</option>
							</select>		 
				   		</div>
					</div>
				</div>

				<!-- Headband -->
				<div class="form-group">
						<div class="row mt-2">
							<div class="col-sm-4">
								<label>Headband</label>
							</div>
							<div class="col-sm-8">
								<select class="form-select form-select-lg" aria-label="headband">
								  <option value="">Layak</option>
								  <option value="">Tidak Layak</option>
								</select>		 
					   		</div>
						</div>
				</div>
    		</div>

    		<div class="col-md-6">
    			<!--Cartridge-->
				<div class="form-group">
					<div class="row mt-2">
						<div class="col-sm-4">
							<label>Cartridge</label>
						</div>
						<div class="col-sm-8">
							<select class="form-select form-select-lg" aria-label="cartridge">
							  <option value="">Layak</option>
							  <option value="">Tidak Layak</option>
							</select>		 
				   		</div>
					</div>
				</div>

				<!--MASK -->
				<div class="form-group">
						<div class="row mt-2">
							<div class="col-sm-4">
								<label>Mask</label>
							</div>
							<div class="col-sm-8">
								<select class="form-select form-select-lg" aria-label="mask">
								  <option value="">Layak</option>
								  <option value="">Tidak Layak</option>
								</select>		 
					   		</div>
						</div>
				</div>
    		</div>
		</div>
	</div>

	<!-- COVERALL-->
	<div class="card-body mt-3 shadow rounded">
		<h4>Coverall</h4>
		<div class="row">
			<div class="col-md-6">
				<div class="form-group">

					<!--Ada/Tidak -->
					<div class="row mt-2">
						<div class="col-sm-4">
							<label>Ada/Tidak</label>
						</div>
						<div class="col-sm-8">
							<select class="form-select form-select-lg" aria-label="coverall-ada-tidak">
							  <option value="">Ada</option>
							  <option value="">Tidak</option>
							</select>		 
				   		</div>
					</div>
				</div>
    		</div>

    		<!--KONDISI -->
    		<div class="col-md-6">
				<div class="form-group">
					<div class="row mt-2">
						<div class="col-sm-4">
							<label>Kondisi</label>
						</div>
						<div class="col-sm-8">
							<select class="form-select form-select-lg" aria-label="kondisi-coverall">
							  <option value="">Layak</option>
							  <option value="">Tidak Layak</option>
							</select>		 
					   	</div>
					</div>
				</div>
    		</div>
		</div>
	</div>
</div>