<style>
	.form-select{
		min-width: 100%;
	}
</style>
<div class="apd-wajib">
	<!-- HELMET-->
	<div class="card-body mt-3 shadow rounded">
		<h4>Helmet</h4>
		<div class="row">
			<div class="col-md-6">
				<div class="form-group">
					<!--Ada/Tidak -->
					<div class="row mt-2">
						<div class="col-sm-4">
							<label>Ada/Tidak</label>
						</div>
						<div class="col-sm-8">
							<select class="form-select form-select-lg" aria-label="helm-ada-tidak">
							  <option value="">Ada</option>
							  <option value="">Tidak</option>
							</select>		 
				   		</div>
					</div>

					<!--Chin Strap -->
					<div class="form-group">
						<div class="row mt-2">
							<div class="col-sm-4">
								<label>Chin Strap</label>
							</div>
							<div class="col-sm-8">
								<select class="form-select form-select-lg" aria-label="chin-strap">
								  <option value="">Layak</option>
								  <option value="">Tidak Layak</option>
								</select>		 
					   		</div>
						</div>
					</div>

					<!--Expired Date -->
					<div class="form-group">
						<div class="row mt-2">
							<div class="col-sm-4">
								<label>Expired</label>
							</div>
							<div class="col-sm-8">
								<select class="form-select form-select-lg" aria-label="exp-date">
								  <option value="">Layak</option>
								  <option value="">Tidak Layak</option>
								</select>		 
					   		</div>
						</div>
					</div>
				</div>
    		</div>

    		<div class="col-md-6">
    				<!--Shell -->
					<div class="row mt-2">
						<div class="col-sm-4">
							<label>Shell</label>
						</div>
						<div class="col-sm-8">
							<select class="form-select form-select-lg" aria-label="shell">
							  <option value="">Layak</option>
							  <option value="">Tidak Tidak Layak</option>
							</select>		 
				   		</div>
					</div>

					<!--Suspension -->
					<div class="form-group">
						<div class="row mt-2">
							<div class="col-sm-4">
								<label>Suspension</label>
							</div>
							<div class="col-sm-8">
								<select class="form-select form-select-lg" aria-label="suspension">
								  <option value="">Layak</option>
								  <option value="">Tidak Layak</option>
								</select>		 
					   		</div>
						</div>
					</div>

					<!--Stiker -->
					<div class="form-group">
						<div class="row mt-2">
							<div class="col-sm-4">
								<label>Stiker</label>
							</div>
							<div class="col-sm-8">
								<select class="form-select form-select-lg" aria-label="stiker">
								  <option value="">Layak</option>
								  <option value="">Tidak Layak</option>
								</select>		 
					   		</div>
						</div>
					</div>
    		</div>
		</div>
	</div>

	<!-- SEPATU-->
	<div class="card-body mt-3 shadow rounded">
		<h4>Sepatu</h4>
		<div class="row">
			<div class="col-md-6">
				<div class="form-group">
					<!--Ada/Tidak -->
					<div class="row mt-2">
						<div class="col-sm-4">
							<label>Ada/Tidak</label>
						</div>
						<div class="col-sm-8">
							<select class="form-select form-select-lg" aria-label="sepatu-ada-tidak">
							  <option value="">Ada</option>
							  <option value="">Tidak</option>
							</select>		 
				   		</div>
					</div>

					<!--Outsol -->
					<div class="form-group">
						<div class="row mt-2">
							<div class="col-sm-4">
								<label>Out Sol</label>
							</div>
							<div class="col-sm-8">
								<select class="form-select form-select-lg" aria-label="outsol">
								  <option value="">Layak</option>
								  <option value="">Tidak Layak</option>
								</select>		 
					   		</div>
						</div>
					</div>
				</div>
    		</div>

    		<!--Steel Toe Cap -->
    		<div class="col-md-6">
					<div class="form-group">
						<div class="row mt-2">
							<div class="col-sm-4">
								<label>Steel Toe Cap</label>
							</div>
							<div class="col-sm-8">
								<select class="form-select form-select-lg" aria-label="steel-toe">
								  <option value="">Layak</option>
								  <option value="">Tidak Layak</option>
								</select>		 
					   		</div>
						</div>
					</div>
    		</div>
		</div>
	</div>

	<!-- SERAGAM-->
	<div class="card-body mt-3 shadow rounded">
		<h4>Seragam</h4>
		<div class="row">
			<div class="col-md-6">
				<div class="form-group">
					<!--Ada/Tidak -->
					<div class="row mt-2">
						<div class="col-sm-4">
							<label>Ada/Tidak</label>
						</div>
						<div class="col-sm-8">
							<select class="form-select form-select-lg" aria-label="seragam-ada-tidak">
							  <option value="">Ada</option>
							  <option value="">Tidak</option>
							</select>		 
				   		</div>
					</div>

					<!--Kain -->
					<div class="form-group">
						<div class="row mt-2">
							<div class="col-sm-4">
								<label>Kain</label>
							</div>
							<div class="col-sm-8">
								<select class="form-select form-select-lg" aria-label="kain">
								  <option value="">Layak</option>
								  <option value="">Tidak Layak</option>
								</select>		 
					   		</div>
						</div>
					</div>
				</div>
    		</div>

    		<div class="col-md-6">
    			<!--Reflektor -->
					<div class="form-group">
						<div class="row mt-2">
							<div class="col-sm-4">
								<label>Reflektor</label>
							</div>
							<div class="col-sm-8">
								<select class="form-select form-select-lg" aria-label="reflektor">
								  <option value="">Layak</option>
								  <option value="">Tidak Layak</option>
								</select>		 
					   		</div>
						</div>
					</div>
    		</div>
		</div>
	</div>
</div>