<div class="container-fluid">
	<h2 class="mb-3 mt-3">Data Pekerja</h2>
	<a class="btn btn-primary text-white mb-3"><img src="assets/plus_circle.png" class="mr-2" href="#">Tambah Data</a>
	<div class="pekerja">
		<div class="row">
		    <div class="col-lg-3">
		    	<div class="card card-pekerja shadow">
					<div class="card-body">
						<h5>PRITA DYAH A</h5>
						<p>NPP. 180411100125</p>
						<button class="btn btn-sm btn-danger float-right"><i class="fas fa-trash-can mr-2"></i>Hapus</button>
						<button class="btn btn-sm btn-detail float-right mr-2 text-white" style="background-color: #2e3092;"><i class="fa-solid fa-circle-info mr-2"></i></i>Detail</button>
					</div>
				</div>
		    </div>

		    <div class="col-lg-3">
		    	<div class="card card-pekerja shadow">
					<div class="card-body">
						<h5>PRITA DYAH A</h5>
						<p>NPP. 180411100125</p>
						<button class="btn btn-sm btn-danger float-right"><i class="fas fa-trash-can mr-2"></i>Hapus</button>
						<button class="btn btn-sm btn-detail float-right mr-2 text-white" style="background-color: #2e3092;"><i class="fa-solid fa-circle-info mr-2"></i></i>Detail</button>
					</div>
				</div>
		    </div>

		    <div class="col-lg-3">
		    	<div class="card card-pekerja shadow">
					<div class="card-body">
						<h5>PRITA DYAH A</h5>
						<p>NPP. 180411100125</p>
						<button class="btn btn-sm btn-danger float-right"><i class="fas fa-trash-can mr-2"></i>Hapus</button>
						<button class="btn btn-sm btn-detail float-right mr-2 text-white" style="background-color: #2e3092;"><i class="fa-solid fa-circle-info mr-2"></i></i>Detail</button>
					</div>
				</div>
		    </div>

		    <div class="col-lg-3">
		    	<div class="card card-pekerja shadow">
					<div class="card-body">
						<h5>PRITA DYAH A</h5>
						<p>NPP. 180411100125</p>
						<button class="btn btn-sm btn-danger float-right"><i class="fas fa-trash-can mr-2"></i>Hapus</button>
						<button class="btn btn-sm btn-detail float-right mr-2 text-white" style="background-color: #2e3092;"><i class="fa-solid fa-circle-info mr-2"></i></i>Detail</button>
					</div>
				</div>
		    </div>
		</div>

	</div>
	<nav class="paginationData mx-auto mt-4" aria-label="Page navigation">
	  <ul class="pagination">
	    <li class="page-item"><a class="page-link" href="#">Previous</a></li>
	    <li class="page-item"><a class="page-link" href="#">1</a></li>
	    <li class="page-item"><a class="page-link" href="#">2</a></li>
	    <li class="page-item"><a class="page-link" href="#">3</a></li>
	    <li class="page-item"><a class="page-link" href="#">Next</a></li>
	  </ul>
	</nav>
</div>