<div class="container container-fluid mt-3 ml-3">
	<div class="judul">
		<h3 class="mt-3">Data Pekerja</h3>
	</div>
	<a href="#"><button class="btn text-light mt-3" style="background: #2e3092;">Tambah data</button></a>
		    	<div class="row">
		    		<div class="col-sm-3">
		    			<div class="card card-karyawn rounded-lg shadow mt-3">
							<div class="card-body">
								<h6>PRITA DYAH A</h6>
								<a>NPP. 180411100125</a>

								<div class="row mt-3">
									<button class="btn btn-sm text-light btn-simpan mr-2" style="background: #2e3092;">Simpan</button>
									<button class="btn btn-sm btn-danger text-black float-right btn-hapus" >Hapus</button>
								</div>								
						  	</div>
						</div>
		    		</div>
		    		<div class="col-sm-3">
		    			<div class="card card-karyawn rounded-lg shadow mt-3">
							<div class="card-body">
								<h6>PRITA DYAH A</h6>
								<a>NPP. 180411100125</a>
								<div class="row mt-3">
									<button class="btn btn-sm text-light btn-simpan mr-2" style="background: #2e3092;">Simpan</button>
									<button class="btn btn-sm btn-danger text-black float-right btn-hapus" >Hapus</button>
								</div>								
						  	</div>
						</div>
		    		</div>
		    		<div class="col-sm-3">
		    			<div class="card card-karyawn rounded-lg shadow mt-3">
							<div class="card-body">
								<h6>PRITA DYAH A</h6>
								<a>NPP. 180411100125</a>
								<div class="row mt-3">
									<button class="btn btn-sm text-light btn-simpan mr-2" style="background: #2e3092;">Simpan</button>
									<button class="btn btn-sm btn-danger text-black float-right btn-hapus" >Hapus</button>
								</div>								
						  	</div>
						</div>
		    		</div>

		    		<div class="col-sm-3">
		    			<div class="card card-karyawn rounded-lg shadow mt-3">
							<div class="card-body">
								<h6>PRITA DYAH A</h6>
								<a>NPP. 180411100125</a>
								<div class="row mt-3">
									<button class="btn btn-sm text-light btn-simpan mr-2" style="background: #2e3092;">Simpan</button>
									<button class="btn btn-sm btn-danger text-black float-right btn-hapus" >Hapus</button>
								</div>								
						  	</div>
						</div>
		    		</div>

		    	</div>
</div>