<div class="headerbar">
    <nav class="navbar navbar-light bg-light">
        <div class="brand g-0">
            <a href="#menu-2" class="btn btn-default" id="menu-2"><i class="fas fa-bars"></i></a>
            <span class="navbar-brand"><h4>Pekerja</h4></span>
        </div>
        <div class="profil" id="navbar-list-4">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-black" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <img src="assets/nav.png>" width="40" height="40" class="rounded-circle">
                            Prita Dyah Anindhita
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="">Log Out</a>
                    </div>
                </li>   
            </ul>
        </div>
    </nav>
</div>