<nav class="navbar headerbar bg-light navbar-expand-sm shadow">

    <a class="navbar-brand font-weight-bold"><i href="#menu-2" id="menu-2" class="fas fa-bars mr-3"></i>Inspeksi APD</a>

    <!--Membuat Toggler Icon untuk Menu-->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-list-4" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    
    <!--profil-->
    <div class="collapse navbar-collapse w-100 order-3 dual-collapse2" id="navbar-list-4">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Prita Dyah Anindhita
                    <img src="" width="40" height="40" class="rounded-circle ml-2">
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="#">Log Out</a>
                </div>
          </li>   
        </ul>
    </div>

</nav>