<style>
	.form-select{
		min-width: 100%;
	}
</style>
<div class="tambahan">
	<!-- Keterangan dan Dokumentasi-->
	<div class="card-body mt-3 shadow rounded">
		<h4>Dokumentasi</h4>
		<div class="row">
			<div class="col-md-6">
				<div class="form-group">
					<!-- Keterangan -->
					<div class="row mt-2">
						<div class="col-sm-4">
							<label>Keterangan</label>
						</div>
						<div class="col-sm-8">
							<input type="text" name="keterangan" class="form-control" placeholder="Tulis keterangan disini">	 
				   		</div>
					</div>

					<!--Dokumentasi -->
					<div class="form-group">
						<div class="row mt-2">
							<div class="col-sm-4">
								<label>Dokumentasi</label>
							</div>
							<div class="col-sm-8">
								<input type="file">		 
					   		</div>
						</div>
					</div>
				</div>
    		</div>
		</div>
	</div>
</div>